### ISSUE TITLE
💡Is the update pattern (data flow) documented?

### ISSUE THREAD

**Issue by ccdejene** [emmaoudmaijer/frontend-data#11]
Ik kan nog niet helemaal zien in je pattern de data wordt geüpdate.
Je code leg je wel goed uit alleen weet ik niet zeker of je iets van een filter gebruikt waarbij de barchart ook daadwerkelijk door nieuwe data.

**Comment by emmaoudmaijer** [comment]
Opgelost! Thanks voor je feedback!
