### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by MarcKunst** [emmaoudmaijer/frontend-data#14]
- [x] Concept en proces: Beschrijf iets duidelijker welke data je nodig hebt om je visualisatie te realiseren. Beschrijf de variable die je nodig hebt vanuit je sparql query.

- [x] Concept en proces: Bij uitwerking staat nu een aantal keer "uitwerking" maar dit zijn geen links

- [x]  Update wiki ontbreekt

- [x] Data uit sparql: laat naast de queries ook een screenshot zien van de JSON die uiteindelijk uit de data komt.

- [x] frontend week 1 en 2 zijn nog vrij leeg. Weet niet of er een onderwerp ik zou moeten komen die belangrijk is voor je beoordeling.

- [x] Reflectie nog toevoegen

**Comment by emmaoudmaijer** [comment]
Thanks voor je feedback!!
