### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [emmaoudmaijer/frontend-data#2]
Hi Emma, ik vind je code over het algemeen prima en clean, je verliest naar mate je verder komt wel een beetje de indentatie uit het oog. Ik zie ook dat je andere functies probeert toe te voegen voor meer interactie met de barchart, je zou deze wat beter / passender kunnen integreren in je codebase. Kijk verder nog even goed naar de manier waarop je je code opdeelt, en of je niet wat praktischer kunt fragmenteren. Veel succes!

**Comment by emmaoudmaijer** [comment]
Thanks voor je feedback!! Ik ga er naar kijken
